access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH:access-refresh-token-keys/access-token.key}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH:access-refresh-token-keys/access-token.pub}

refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH:access-refresh-token-keys/refresh-token.key}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH:access-refresh-token-keys/refresh-token.pub}

spring:
  application:
    name: backend
  profiles:
    active: dev
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://paf:paf123@cluster0.mongodb.net/paf_database?retryWrites=true&w=majority}
      database: ${MONGODB_DATABASE:paf_database}
      auto-index-creation: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG

