package com.example.backend.models;

import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.Date;

// Represents a post made by a user within a cooking community group
@Document(collection = "groupPosts")
@Getter
@Setter
public class GroupPost {

    // Unique identifier for each post
    @Id
    private String id;

    // The ID of the group to which the post belongs
    private String groupId;

    // The ID of the user who created the post
    private String userId;

    // The content of the post (text)
    private String content;

    // The timestamp when the post was created
    private Date timestamp;

    // URL for any media attached to the post (e.g., image, video)
    private String mediaUrl;

    // The type of media attached to the post (e.g., "image", "video")
    private String mediaType;
    
    // Default constructor that sets the timestamp to the current date
    public GroupPost() {
        this.timestamp = new Date();
    }

    // Getters and Setters are automatically, generated by Lombok (@Getter, @Setter)
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public String getMediaUrl() {
        return mediaUrl;
    }

    public void setMediaUrl(String mediaUrl) {
        this.mediaUrl = mediaUrl;
    }

    public String getMediaType() {
        return mediaType;
    }

    public void setMediaType(String mediaType) {
        this.mediaType = mediaType;
    }
}
